addons:
  postgresql: 9.2
  code_climate:
      repo_token: 915fb7899aed5496ffa2b60cb9b6f208164427996dc2cbc3cd9b2b6cece668f0
after_success:
  - bundle exec codeclimate-test-reporter
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
dist: trusty
language: ruby
rvm:
  - 2.4.1
script:
  - bundle exec rails db:migrate RAILS_ENV=test
deploy:
  provider: heroku
  api_key: 
    secure: afe82543-057f-4134-a5ec-d41edcee13a1
  on:
    branch: master
    rvm: 2.4.1
  run: "rake db: migrate"